# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

# Below is an example of intersphinx mapping declaration
# Add more mappings depending on what manual you want to link to
# Remove entirely if you don't need cross-linking

---
conf.py:
  copyright: 2014-2015
  project: Ameos Mail redirect
  version: 1.1
  release: 1.1.5
  html_theme_options:
    github_repository: ameos/ameos_mailredirect
    github_branch: master
  latex_documents:
  - - Index
    - ameos_mailredirect.tex
    - Mail redirect for dev
    - Ameos Team
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  latex_show_pagerefs: True
...
